// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.http.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetHttpRetryArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetHttpRetryArgs Empty = new GetHttpRetryArgs();

    /**
     * The number of times the request is to be retried. For example, if 2 is specified, the request will be tried a maximum of 3 times.
     * 
     */
    @Import(name="attempts")
    private @Nullable Output<Integer> attempts;

    /**
     * @return The number of times the request is to be retried. For example, if 2 is specified, the request will be tried a maximum of 3 times.
     * 
     */
    public Optional<Output<Integer>> attempts() {
        return Optional.ofNullable(this.attempts);
    }

    /**
     * The maximum delay between retry requests in milliseconds.
     * 
     */
    @Import(name="maxDelayMs")
    private @Nullable Output<Integer> maxDelayMs;

    /**
     * @return The maximum delay between retry requests in milliseconds.
     * 
     */
    public Optional<Output<Integer>> maxDelayMs() {
        return Optional.ofNullable(this.maxDelayMs);
    }

    /**
     * The minimum delay between retry requests in milliseconds.
     * 
     */
    @Import(name="minDelayMs")
    private @Nullable Output<Integer> minDelayMs;

    /**
     * @return The minimum delay between retry requests in milliseconds.
     * 
     */
    public Optional<Output<Integer>> minDelayMs() {
        return Optional.ofNullable(this.minDelayMs);
    }

    private GetHttpRetryArgs() {}

    private GetHttpRetryArgs(GetHttpRetryArgs $) {
        this.attempts = $.attempts;
        this.maxDelayMs = $.maxDelayMs;
        this.minDelayMs = $.minDelayMs;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetHttpRetryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetHttpRetryArgs $;

        public Builder() {
            $ = new GetHttpRetryArgs();
        }

        public Builder(GetHttpRetryArgs defaults) {
            $ = new GetHttpRetryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param attempts The number of times the request is to be retried. For example, if 2 is specified, the request will be tried a maximum of 3 times.
         * 
         * @return builder
         * 
         */
        public Builder attempts(@Nullable Output<Integer> attempts) {
            $.attempts = attempts;
            return this;
        }

        /**
         * @param attempts The number of times the request is to be retried. For example, if 2 is specified, the request will be tried a maximum of 3 times.
         * 
         * @return builder
         * 
         */
        public Builder attempts(Integer attempts) {
            return attempts(Output.of(attempts));
        }

        /**
         * @param maxDelayMs The maximum delay between retry requests in milliseconds.
         * 
         * @return builder
         * 
         */
        public Builder maxDelayMs(@Nullable Output<Integer> maxDelayMs) {
            $.maxDelayMs = maxDelayMs;
            return this;
        }

        /**
         * @param maxDelayMs The maximum delay between retry requests in milliseconds.
         * 
         * @return builder
         * 
         */
        public Builder maxDelayMs(Integer maxDelayMs) {
            return maxDelayMs(Output.of(maxDelayMs));
        }

        /**
         * @param minDelayMs The minimum delay between retry requests in milliseconds.
         * 
         * @return builder
         * 
         */
        public Builder minDelayMs(@Nullable Output<Integer> minDelayMs) {
            $.minDelayMs = minDelayMs;
            return this;
        }

        /**
         * @param minDelayMs The minimum delay between retry requests in milliseconds.
         * 
         * @return builder
         * 
         */
        public Builder minDelayMs(Integer minDelayMs) {
            return minDelayMs(Output.of(minDelayMs));
        }

        public GetHttpRetryArgs build() {
            return $;
        }
    }

}
