provider: http
major-version: 0
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
esc:
  enabled: true
env:
  HTTP_TOKEN: ${{ secrets.HTTP_TOKEN }}
pulumiConvert: 1
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
