// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Http.Outputs
{

    [OutputType]
    public sealed class GetHttpRetryResult
    {
        /// <summary>
        /// The number of times the request is to be retried. For example, if 2 is specified, the request will be tried a maximum of 3 times.
        /// </summary>
        public readonly int? Attempts;
        /// <summary>
        /// The maximum delay between retry requests in milliseconds.
        /// </summary>
        public readonly int? MaxDelayMs;
        /// <summary>
        /// The minimum delay between retry requests in milliseconds.
        /// </summary>
        public readonly int? MinDelayMs;

        [OutputConstructor]
        private GetHttpRetryResult(
            int? attempts,

            int? maxDelayMs,

            int? minDelayMs)
        {
            Attempts = attempts;
            MaxDelayMs = maxDelayMs;
            MinDelayMs = minDelayMs;
        }
    }
}
