# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetHttpRetryResult',
]

@pulumi.output_type
class GetHttpRetryResult(dict):
    def __init__(__self__, *,
                 attempts: Optional[_builtins.int] = None,
                 max_delay_ms: Optional[_builtins.int] = None,
                 min_delay_ms: Optional[_builtins.int] = None):
        """
        :param _builtins.int attempts: The number of times the request is to be retried. For example, if 2 is specified, the request will be tried a maximum of 3 times.
        :param _builtins.int max_delay_ms: The maximum delay between retry requests in milliseconds.
        :param _builtins.int min_delay_ms: The minimum delay between retry requests in milliseconds.
        """
        if attempts is not None:
            pulumi.set(__self__, "attempts", attempts)
        if max_delay_ms is not None:
            pulumi.set(__self__, "max_delay_ms", max_delay_ms)
        if min_delay_ms is not None:
            pulumi.set(__self__, "min_delay_ms", min_delay_ms)

    @_builtins.property
    @pulumi.getter
    def attempts(self) -> Optional[_builtins.int]:
        """
        The number of times the request is to be retried. For example, if 2 is specified, the request will be tried a maximum of 3 times.
        """
        return pulumi.get(self, "attempts")

    @_builtins.property
    @pulumi.getter(name="maxDelayMs")
    def max_delay_ms(self) -> Optional[_builtins.int]:
        """
        The maximum delay between retry requests in milliseconds.
        """
        return pulumi.get(self, "max_delay_ms")

    @_builtins.property
    @pulumi.getter(name="minDelayMs")
    def min_delay_ms(self) -> Optional[_builtins.int]:
        """
        The minimum delay between retry requests in milliseconds.
        """
        return pulumi.get(self, "min_delay_ms")


