// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { GetHttpArgs, GetHttpResult, GetHttpOutputArgs } from "./getHttp";
export const getHttp: typeof import("./getHttp").getHttp = null as any;
export const getHttpOutput: typeof import("./getHttp").getHttpOutput = null as any;
utilities.lazyLoad(exports, ["getHttp","getHttpOutput"], () => require("./getHttp"));

export * from "./provider";
import { Provider } from "./provider";


// Export sub-modules:
import * as types from "./types";

export {
    types,
};
pulumi.runtime.registerResourcePackage("http", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:http") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
